### ISSUE TITLE
WECHAT_PAY_MANAGER 无法使用

### ISSUE THREAD

**Issue by leelii** [klover2/nest-wechatpay-node-v3-ts#2]
nest框架，在servive中下面这行会报错
`constructor(@Inject(WECHAT_PAY_MANAGER) private wxPay: WxPay) {}`

报错信息如下：
`Error: Nest can't resolve dependencies of the WeiXinService (?). Please make sure that the argument WECHAT_PAY_MANAGER at index [0] is available in the WeiXinModule context`

**Comment by klover2** [comment]
![image](https://user-images.githubusercontent.com/49548817/230809107-5a245519-047e-4a48-8ee0-e4f6f1eb6133.png)
是否导入了这个module

**Comment by wulianyougithub** [comment]
同样的问题，已经在appModule中导入了，和文档中描述的一样，这个问题是怎么解决的

**Comment by klover2** [comment]
> 同样的问题，已经在appModule中导入了，和文档中描述的一样，这个问题是怎么解决的

我这个是列子 正常使用你应该放在你自己的子module 里面

**Comment by Groupguanfang** [comment]
作者其实应该加一个`global: boolean`的配置，这样当我们指定`global: true`的时候，就可以全局使用这个模块了。

nest.js的DynamicModule是有这个的，只是作者没有把这个选项透传出来好像

@klover2 看看能不能把这个加上？

**Comment by klover2** [comment]
> `global: true`的时

已经支持 请使用 1.0.2

**Comment by Groupguanfang** [comment]
> > `global: true`的时
> 
> 
> 
> 已经支持 请使用 1.0.2

Wow，nice
