### ISSUE TITLE
Inject 这个装饰器不存在啊

### ISSUE THREAD

**Issue by meepo-it** [klover2/nest-wechatpay-node-v3-ts#3]
nestjs 中，并没有 Inject 方法

**Comment by klover2** [comment]
> nestjs 中，并没有 Inject 方法

仅支持 nextjs + ts中使用

**Comment by niki571** [comment]
> > nestjs 中，并没有 Inject 方法
> 
> 仅支持 nextjs + ts中使用

到底是nestjs还是nextjs？这个项目不是nest-wechatpay-node-v3-ts吗？

**Comment by niki571** [comment]
> nestjs 中，并没有 Inject 方法

有的
`import { Inject, Injectable } from '@nestjs/common';`
